name: Publish New Version

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17.1.0
      - run: npm i
      #- run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.npm_secret }}

      # - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 17.1.0
      #     registry-url: https://registry.npmjs.org/
      # - run: curl https://npmjs.org/install.sh | sh
      # - run: npm i
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.npm_secret}}
